<a href="https://colab.research.google.com/github/skekek2/-/blob/main/13%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#필요한 라이브러리 불러오기
from sklearn.linear_model import LinearRegression
import numpy as np

In [ ]:
#Feature로 사용할 거리 ×를 넘파이 배열로 생성
x=np.array([[1],[2],[3],[4]])
x

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
#x 의 형 태 를 확 인
x. shape

(4, 1)

In [ ]:
#A회사의 target(y)인 요금을 넘파이 배열에 저장
y_a=np.array([5000,7000,8400,10500])
y_a

array([ 5000,  7000,  8400, 10500])

In [ ]:
y_a. shape

(4,)

In [ ]:
#A회사의 모델을 생성하고 학습시킨 후 학습된 모델에서 기울기와 절편값 추출
model_a=LinearRegression()
model_a.fit(x,y_a)#적합
w1=model_a.coef_
b1=model_a.intercept_
print(w1, b1)

[1790.] 3250.0


In [ ]:
#B회사의 모델을 생성하고 학습시킨 후 학습된 모델에서 기울기와 절편값 추출
model_b=LinearRegression()
y_b=[3100,5400,7900,10900]
model_b.fit(x.y_b)#적합
w2=model_b.coef_
b2=model_b.intercept_
print(w2, b2)

AttributeError: 'numpy.ndarray' object has no attribute 'y_b'

In [ ]:
#회귀식을 이용해 20km를 이동했을 경우 각 회사별 요금 예속
x= np.array([20])
cost_a=w1*x_+b1
cost_a

In [ ]:
cost_b=w2*x_+b2
cost_b

In [ ]:
x=(3250-350)/(2590-1790)

x

3.625

In [ ]:
#사이킷런의 predict()함수를 이용해 예측
x=np.array(range(1,21))
x=x.reshape(-1.1)
y_a=model_a.predict(x)
y_a

TypeError: expected a sequence of integers or a single integer, got '-1.1'

In [ ]:
x=np.array(range(1,21))#1~20
x. shape

In [ ]:
#사이킷런의 predict()함수를 이용해 예측
y_bemodel_b.predict(x)
y_b

In [ ]:
#산점도
import matplotlib.pyplot as plt
x=np.array([[1].[2], [3] I[4]])
y_a=model_a.predict(x)
y_b=model_b.predict(x)
plt.plot(x, y_a,'*r')
plt.plot(x,y_b,'^g')

In [ ]:
import matplotlib.pyplot as plt
#실제값
x=np.array([1.2,3,4])
y_a=[5000,7000,8400,10500]
y_b=[3100,5400,7900,10900]
plt.plot(x,y_a, '*r')
plt.plot(x.y_b,'^g')
#예측값
x=np.array(range(1,14))
x=x.reshape(-1,1)
y_a=model_a.predict(x)
plt.plot(x,y_a,'r')

#학습한 모델을 이용해 예측한 값과 실제 값을 그래프로 그려보자

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
import numpy as np

In [ ]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [ ]:
x.shape

(4,)

In [ ]:
x=x.reshape(-1.1)
x.shape

TypeError: expected a sequence of integers or a single integer, got '-1.1'

In [ ]:
y_a=np.array([5000, 7000, 8400, 10500])

y_a

In [ ]:
y_a.shape

In [ ]:
model_a=LinearRegression()

In [ ]:
model_fit(x.)

In [ ]:
#필요한 라이브러리 불려오기
from skleark.linear_model import LinearRegression
import numpy as np

In [ ]:
model_a.fit(x.y_a)

In [ ]:
y=model_a.predict(x)

y

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(x,y_a,'*r')

In [ ]:
import matplotlib.pyplot as plt
x=np.array([[1],[2],[3],[4]])
y_b=np.array([3100, 5400, 7900,10900])
plt.plot(x,y_b,'^g')
model_b=LinearRegression()
model_b.fit(x.y_a)
x=np.array(range(1,21)).reshape(-1,1)
y=model_b.predict(x)

y
plt.plot(x.y,'r')

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from sklearn.datasets import load_iris
iris=load_iris()

In [ ]:
iris.keys()

In [ ]:
iris

In [ ]:
print(iris['DESCR'])

In [ ]:
#독립변수 data와 feature_names를 이용하여 데이터 프레임 생성
df_iris=pd.DataFrame(iris['data'].columns=iris.feature_names)
df_iris

In [ ]:
#데이터프레임 정보
df_iris.info()

In [ ]:
# 데 이 터 프 레 임 설 명 , 통 계
df_iris.describe()

In [ ]:
#꽃받침의 길이와 너비를 이용한 산점도
color=['r','g','b']
for idx, row in df_iris[['sepal length (cm)','sepal width (cm) ']].iterrows():
  c=iris['target'] [idx]
  plt.scatter(row['sepal length (cm)'].row['sepal width (cm) '],color=color[c], alpha =5)
plt.xlabel('sepal length (cm)')
plt.ylabel('sepal width (cm)')
plt.grid(True)

plt.show()

In [ ]:
iris['target']

In [ ]:
#꽃잎의 길이와 너비를 이용한 산점도
color=['r','g','b']
for idx, row in df_iris[['petal length (cm)', 'petal width (cm) ']].iterrows():
  c=iris['target'][idx]
  plt.scatter(row['petal length (cm)'].row['petal width (cm)'].color=color[c],alpha =. 5)
plt.xlabel('petal length (cm)')
plt.ylabel('petal width (cm) ')
plt.grid(True)

plt.show()

In [ ]:
#결측값 확인
df_iris.isnull().sum()

In [ ]:
#새로운 feature 생성
df_iris['sepal/petal length']=df_iris['sepal length (cm) ']/df_iris['petal length (cm)']
df_iris['sepal/petal width']=df_iris['sepal width (cm) ']/df_iris['petal width (cm)']
df_iris

NameError: name 'df_iris' is not defined

In [ ]:
mms=MinMaxScaler()
dfliris=mms.fit_transform(df_iris)
df_iris= pd.DataFrame(df_iris, columns=iris['feature_names']+['sepal/petal length', 'sepal/petal width'])
df_iris
#iris=pd.DataFrame(iris)

from sklearn.preprocessing import MinMaxScaler

In [ ]:
#시각화

#꽃잎의 길이와 너비를 이용한 산점도
color=['r','g','b']
for idx, row in df_iris[['sepal/petal length','sepal/petal width']].iterrows():
  c=iris['target'][idx]
  plt.scatter(row['sepal/petal length'].row['sepal/petal width'].color=color[c],alpha =. 5)
plt.xlabel('sepal/petal length')
plt.ylabel('sepal/petal width')
plt.grid(True)

plt.show()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(df_iris, iris['target'], test_size=0.2, random_state=42)

In [ ]:
# 모 델 적 합 ( 학 습 )
from sklearn.neighbors import KNeighborsClassifier
model= KNeighborsClassifier()
model.fit(X_train, y_train)
model.score(X_train,y_train)

In [ ]:
# 모 델 평가

model.score(X_test, y_test)

In [ ]:
# 결과 예측
y_pred=model.prediot(rX_test)

In [ ]:
print(y_pred)
print(y_test)